before_script:
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY

stages:
  - build

build-master:
  stage: build
  services:
    - docker:dind
  script:
    - docker build --tag "${CI_REGISTRY_IMAGE}:latest" .
    - docker push "$CI_REGISTRY_IMAGE"
  only:
    - master

build-tag:
  stage: build
  services:
    - docker:dind
  script:
    - docker build --tag "${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG}" .
    - docker push "${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG}"
  only:
    - tags

